In [27]:
import numpy as np
import pandas as pd

In [2]:
A = np.array(
    [[1, 1], [2, -1], [1,2]]
)

In [3]:
A

array([[ 1,  1],
       [ 2, -1],
       [ 1,  2]])

In [6]:
A.T 

array([[ 1,  2,  1],
       [ 1, -1,  2]])

In [7]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [11]:
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [12]:
x

array([1, 2, 3, 4, 5])

In [10]:
np.dot(A, x)

array([26, 30])

In [14]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [16]:
np.dot(B, A) 

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [18]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [22]:
A = np.array([x, y, z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [24]:
np.dot(A.T, A)

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [31]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)


In [63]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
sum_count = Count_DF * Price_DF
np.dot(sum_count.values, com)
sum_count.sum(axis=1) - np.dot(sum_count.values, com)

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64