In [2]:
import numpy as np
import pandas as pd

In [3]:
np.array([5, 2]) + np.array([-5, -11])

array([ 0, -9])

In [4]:
np.array([5, 2]) - np.array([-5, -11])

array([10, 13])

In [5]:
np.array([2, 3, 2.5]) * 72 + np.array([120, 150, 190]) + np.array([130, 130, 130]) 

array([394., 496., 500.])

In [6]:
np.array([4, 5]) * 2 + np.array([2, 1]) * -3 + np.array([1, 0]) * 5 

array([7, 7])

In [7]:
np.array([3,4,5,9]) * 200 - np.array([1,5,3,6]) * 400

array([  200, -1200,  -200,  -600])

In [8]:
np.dot(np.array([4,5,-1]), np.array([2,0,1]))


7

In [9]:


Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [10]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [11]:
np,sum(Hut_Paradise_DF['5.Demo two weeks'].values * np.array([10, 20, 30, 15, 5, 40, 20, 8, 20]))

(<module 'numpy' from '/home/vladimir/miniconda3/envs/MIFI_tasks/lib/python3.11/site-packages/numpy/__init__.py'>,
 1348)

In [12]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])


In [13]:
np.dot(v * 2 + w*-3, u)

0

In [14]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [15]:
fam_income = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T

In [16]:
fam_consumption = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T

In [17]:
fam_income_taxes = fam_income - fam_income * 0.13 

In [18]:
fam_income_taxes - fam_consumption

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [19]:
np.dot(np.array([0,1,2,1,2]), np.array([0,-1,1,1,-1]))

0

In [20]:
np.array([[1,3]]).T * np.array([[-3,1]])

array([[-3,  1],
       [-9,  3]])

In [21]:
np.linalg.inv(np.array([[1, 2], [2, 5]])
)

array([[ 5., -2.],
       [-2.,  1.]])

In [22]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [23]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1, v2, v3, v4]).T
np.linalg.matrix_rank(A)

G = np.dot(A.T, A) 

In [24]:
np.linalg.det(G) * (1/ np.linalg.det(G)) 

1.0

In [25]:
np.linalg.inv(G)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [26]:
np.dot(np.array([-1,2,-7,9]), np.array([2,8,2,-1]))

-9

In [27]:
A = np.array([[1,2], [3,7]])
np.linalg.inv(A)

array([[ 7., -2.],
       [-3.,  1.]])

In [28]:
A = np.array([[4, 7], [5, 10]])

np.dot(np.linalg.inv(A), np.array([[20, 30]]).T)

array([[-2.],
       [ 4.]])

In [29]:
w = np.array([[1,1]]).T
A = np.array([[1, -5], [2, 1], [1, 1]])
np.array([[1,2,2]]).T - np.dot(A, w) 

array([[ 5],
       [-1],
       [ 0]])

In [30]:
A = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])
G = np.dot(A.T, A)
inv_G = np.linalg.inv(G)
free_coef = np.array([[1,4,5,0]])
free_coef_AT = np.dot(A.T,free_coef.T)
w = np.dot(inv_G, free_coef_AT)
w

array([[-0.5],
       [ 1.6]])

In [32]:
A = np.array([[1, 0.2, 6]])
w_hat =  np.array([-29.3,-0.26,8.4]).T
np.dot(A, w_hat)


array([21.048])